const data = {
  products: [
    {
      name: 'RAZA',
      slug: 'raza-food',
      category: 'food',
      image: '/images/raza.avif',
      price: 300,
      countInStock: '10',
      brand: 'raza',
      description: 'Perro Adulto Sabor Carne 21 (x Kg Suelto)',
    },
    {
      name: 'PEDIGREE',
      slug: 'pedigree-food',
      category: 'food',
      image: '/images/pedigree.avif',
      price: 600,
      countInStock: '10',
      brand: 'pedigree',
      description: 'Adulto (etapa 2) Carne Pollo Y Cereal 21 (x Kg Suelto)',
    },
    {
      name: 'DOGCHOW',
      slug: 'dogchow-food',
      category: 'food',
      image: '/images/dogchow.avif',
      price: 700,
      countInStock: '10',
      brand: 'dogchow',
      description: 'Adultos Minis Y Pequeños 21kg (x Kg Suelto)',
    },
    {
      name: 'EXCELLENT',
      slug: 'excellent-food',
      category: 'food',
      image: '/images/excellent.avif',
      price: 900,
      countInStock: '10',
      brand: 'excellent',
      description: 'Adult Dog Raza Mediana Y Grande Smart 20 Kg (x Kg Suelto)',
    },
  ],
};
export default data;
